```
[Title] SLP Classification using Tensorflow.Keras
[Author] Yibeck Lee(yibec.Lee@gmail.com)
[Contents]
 - Single-Layer Perceptron Classification for Prediction
```

In [1]:
"""
    A simple neural network written in Keras (TensorFlow backend) to classify the IRIS data
"""

import numpy as np

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam
import pandas as pd

# data = load_iris() # load the iris dataset
df = pd.read_csv("../data_source/iris.csv")
data = df.values
# print(data)
# print(iris_data)
FEATURES = data[:,:4]
LABEL = data[:,-1]
LABEL

Using TensorFlow backend.


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [2]:

x = FEATURES
y_ = LABEL.reshape(-1, 1) # Convert data to a single column
y_ 

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],

In [3]:
# One Hot encode the class labels
encoder = OneHotEncoder(sparse=False)
y = encoder.fit_transform(y_)
print(y)


[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0.

C:\Apps\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [4]:
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.50)

In [5]:
# Split the data for training and testing


# Build the model

model = Sequential()

model.add(Dense(10, input_shape=(4,), activation='relu', name='fc1'))
model.add(Dense(3, activation='softmax', name='output'))

# Adam optimizer with learning rate of 0.001
optimizer = Adam(lr=0.001)
model.compile(optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

print('Neural Network Model Summary: ')
print(model.summary())

# Train the model
model.fit(train_x, train_y, verbose=2, batch_size=5, epochs=200)

# Test on unseen data

results = model.evaluate(test_x, test_y)

print('Final test set loss: {:4f}'.format(results[0]))
print('Final test set accuracy: {:4f}'.format(results[1]))

Neural Network Model Summary: 
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
fc1 (Dense)                  (None, 10)                50        
_________________________________________________________________
output (Dense)               (None, 3)                 33        
Total params: 83
Trainable params: 83
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/200
 - 1s - loss: 2.9108 - acc: 0.2667
Epoch 2/200
 - 0s - loss: 2.5139 - acc: 0.2667
Epoch 3/200
 - 0s - loss: 2.1751 - acc: 0.2667
Epoch 4/200
 - 0s - loss: 1.8937 - acc: 0.2667
Epoch 5/200
 - 0s - loss: 1.6628 - acc: 0.2667
Epoch 6/200
 - 0s - loss: 1.4825 - acc: 0.2667
Epoch 7/200
 - 0s - loss: 1.3468 - acc: 0.1200
Epoch 8/200
 - 0s - loss: 1.2593 - acc: 0.1067
Epoch 9/200
 - 0s - loss: 1.2034 - acc: 0.3200
Epoch 10/200
 - 0s - loss: 1.1607 - acc: 0.3600
Epoch 11/200
 - 0s - loss: 1.1245 -

Epoch 158/200
 - 0s - loss: 0.1574 - acc: 0.9600
Epoch 159/200
 - 0s - loss: 0.1546 - acc: 0.9600
Epoch 160/200
 - 0s - loss: 0.1540 - acc: 0.9733
Epoch 161/200
 - 0s - loss: 0.1515 - acc: 0.9733
Epoch 162/200
 - 0s - loss: 0.1540 - acc: 0.9600
Epoch 163/200
 - 0s - loss: 0.1515 - acc: 0.9600
Epoch 164/200
 - 0s - loss: 0.1485 - acc: 0.9733
Epoch 165/200
 - 0s - loss: 0.1474 - acc: 0.9733
Epoch 166/200
 - 0s - loss: 0.1470 - acc: 0.9733
Epoch 167/200
 - 0s - loss: 0.1461 - acc: 0.9733
Epoch 168/200
 - 0s - loss: 0.1441 - acc: 0.9600
Epoch 169/200
 - 0s - loss: 0.1429 - acc: 0.9733
Epoch 170/200
 - 0s - loss: 0.1430 - acc: 0.9733
Epoch 171/200
 - 0s - loss: 0.1400 - acc: 0.9867
Epoch 172/200
 - 0s - loss: 0.1396 - acc: 0.9733
Epoch 173/200
 - 0s - loss: 0.1383 - acc: 0.9733
Epoch 174/200
 - 0s - loss: 0.1378 - acc: 0.9733
Epoch 175/200
 - 0s - loss: 0.1362 - acc: 0.9867
Epoch 176/200
 - 0s - loss: 0.1367 - acc: 0.9733
Epoch 177/200
 - 0s - loss: 0.1373 - acc: 0.9467
Epoch 178/200
 - 0s 

In [6]:
model.predict(test_x)

array([[9.83389556e-01, 1.66096371e-02, 8.75146895e-07],
       [1.77582160e-06, 2.01066993e-02, 9.79891479e-01],
       [9.20879302e-08, 5.53357648e-03, 9.94466364e-01],
       [7.43227371e-04, 5.58259010e-01, 4.40997720e-01],
       [7.18198571e-05, 1.87433168e-01, 8.12494993e-01],
       [1.10528544e-02, 8.74995112e-01, 1.13952085e-01],
       [9.92133200e-01, 7.86675140e-03, 1.07437380e-07],
       [5.67365214e-06, 5.38594797e-02, 9.46134806e-01],
       [1.57310569e-03, 5.07076681e-01, 4.91350174e-01],
       [4.25300598e-02, 8.88458252e-01, 6.90115914e-02],
       [2.29891948e-03, 8.39978874e-01, 1.57722175e-01],
       [1.39593030e-05, 1.92423552e-01, 8.07562530e-01],
       [4.20174274e-07, 3.54561582e-02, 9.64543402e-01],
       [1.85800821e-03, 7.95588434e-01, 2.02553481e-01],
       [9.81045485e-01, 1.89528260e-02, 1.66820166e-06],
       [2.40193891e-08, 2.39229901e-03, 9.97607708e-01],
       [9.95041430e-01, 4.95842192e-03, 6.05957027e-08],
       [7.38116261e-03, 8.69362

In [7]:
predicted = model.predict_classes(test_x)
print(predicted)

[0 2 2 1 2 1 0 2 1 1 1 2 2 1 0 2 0 1 2 0 1 2 0 2 0 0 2 0 2 2 2 2 0 0 0 0 0
 0 1 1 2 0 1 1 2 1 0 2 0 2 2 0 2 0 1 0 0 1 1 0 2 1 1 1 1 1 0 2 1 0 1 1 0 2
 1]


In [8]:
for i in range(30):
    print(test_y[i],np.argmax(test_y[i]),predicted[i])

[1. 0. 0.] 0 0
[0. 0. 1.] 2 2
[0. 0. 1.] 2 2
[0. 1. 0.] 1 1
[0. 0. 1.] 2 2
[0. 1. 0.] 1 1
[1. 0. 0.] 0 0
[0. 0. 1.] 2 2
[0. 1. 0.] 1 1
[0. 1. 0.] 1 1
[0. 1. 0.] 1 1
[0. 0. 1.] 2 2
[0. 0. 1.] 2 2
[0. 1. 0.] 1 1
[1. 0. 0.] 0 0
[0. 0. 1.] 2 2
[1. 0. 0.] 0 0
[0. 1. 0.] 1 1
[0. 0. 1.] 2 2
[1. 0. 0.] 0 0
[0. 1. 0.] 1 1
[0. 0. 1.] 2 2
[1. 0. 0.] 0 0
[0. 0. 1.] 2 2
[1. 0. 0.] 0 0
[1. 0. 0.] 0 0
[0. 1. 0.] 1 2
[1. 0. 0.] 0 0
[0. 1. 0.] 1 2
[0. 0. 1.] 2 2


In [9]:
from sklearn.metrics import confusion_matrix
actual_label = np.argmax(test_y,axis=1)
confusion_matrix(actual_label, predicted)

array([[26,  0,  0],
       [ 0, 25,  5],
       [ 0,  0, 19]], dtype=int64)

In [10]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(actual_label, predicted)
accuracy

0.9333333333333333

In [11]:
from sklearn.metrics import recall_score
recall = recall_score(actual_label, predicted, average='macro')
recall

0.9444444444444445

In [12]:
from sklearn.metrics import precision_score
precision = precision_score(actual_label, predicted, average='macro')
precision

0.9305555555555555

In [13]:
from sklearn.metrics import f1_score
f1 = f1_score(actual_label, predicted, average='macro')
f1

0.930937279774489