```
[Title] Logistic Regression for Classification using Tensorflow.Keras
[Author] Yibeck Lee(yibec.Lee@gmail.com)
[Contents]
 - Logistic Regression for Classification for Prediction
```

In [1]:
"""
    A simple neural network written in Keras (TensorFlow backend) to classify the IRIS data
"""

import numpy as np

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam
import pandas as pd

# data = load_iris() # load the iris dataset
df = pd.read_csv("../data_source/iris.csv")
data = df.values
# print(data)
# print(iris_data)
FEATURES = data[:,:4]
LABEL = data[:,-1]
LABEL

Using TensorFlow backend.


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [2]:

x = FEATURES
y_ = LABEL.reshape(-1, 1) # Convert data to a single column
y_ 

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],

In [3]:
# One Hot encode the class labels
encoder = OneHotEncoder(sparse=False)
y = encoder.fit_transform(y_)
print(y)


[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0.

C:\Apps\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [4]:
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.50)

In [5]:
# Split the data for training and testing


# Build the model

model = Sequential() 
model.add(Dense(3, input_dim=4, activation='softmax'))


# Adam optimizer with learning rate of 0.001
optimizer = Adam(lr=0.001)
model.compile(optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

print('Neural Network Model Summary: ')
print(model.summary())

# Train the model
model.fit(train_x, train_y, verbose=2, batch_size=5, epochs=200)

# Test on unseen data

results = model.evaluate(test_x, test_y)

print('Final test set loss: {:4f}'.format(results[0]))
print('Final test set accuracy: {:4f}'.format(results[1]))

Neural Network Model Summary: 
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 3)                 15        
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/200
 - 0s - loss: 3.1677 - acc: 0.3333
Epoch 2/200
 - 0s - loss: 3.0750 - acc: 0.3333
Epoch 3/200
 - 0s - loss: 2.9806 - acc: 0.3333
Epoch 4/200
 - 0s - loss: 2.8903 - acc: 0.3333
Epoch 5/200
 - 0s - loss: 2.7964 - acc: 0.3333
Epoch 6/200
 - 0s - loss: 2.7140 - acc: 0.3333
Epoch 7/200
 - 0s - loss: 2.6208 - acc: 0.3333
Epoch 8/200
 - 0s - loss: 2.5403 - acc: 0.3333
Epoch 9/200
 - 0s - loss: 2.4559 - acc: 0.3333
Epoch 10/200
 - 0s - loss: 2.3728 - acc: 0.3333
Epoch 11/200
 - 0s - loss: 2.2848 - acc: 0.3333
Epoch 12/200
 - 0s - loss: 2.2112 - acc: 0.3333
Epoch 13/200
 - 0s - loss: 2.1261 - acc: 0.3467
Epoch 14/200
 - 0s - lo

Epoch 161/200
 - 0s - loss: 0.4702 - acc: 0.8267
Epoch 162/200
 - 0s - loss: 0.4686 - acc: 0.8267
Epoch 163/200
 - 0s - loss: 0.4682 - acc: 0.8133
Epoch 164/200
 - 0s - loss: 0.4667 - acc: 0.8267
Epoch 165/200
 - 0s - loss: 0.4689 - acc: 0.7867
Epoch 166/200
 - 0s - loss: 0.4636 - acc: 0.8267
Epoch 167/200
 - 0s - loss: 0.4621 - acc: 0.8267
Epoch 168/200
 - 0s - loss: 0.4605 - acc: 0.8267
Epoch 169/200
 - 0s - loss: 0.4594 - acc: 0.8267
Epoch 170/200
 - 0s - loss: 0.4582 - acc: 0.8267
Epoch 171/200
 - 0s - loss: 0.4572 - acc: 0.8267
Epoch 172/200
 - 0s - loss: 0.4577 - acc: 0.8400
Epoch 173/200
 - 0s - loss: 0.4544 - acc: 0.8267
Epoch 174/200
 - 0s - loss: 0.4531 - acc: 0.8267
Epoch 175/200
 - 0s - loss: 0.4523 - acc: 0.8267
Epoch 176/200
 - 0s - loss: 0.4509 - acc: 0.8267
Epoch 177/200
 - 0s - loss: 0.4508 - acc: 0.8267
Epoch 178/200
 - 0s - loss: 0.4487 - acc: 0.8400
Epoch 179/200
 - 0s - loss: 0.4472 - acc: 0.8533
Epoch 180/200
 - 0s - loss: 0.4472 - acc: 0.8267
Epoch 181/200
 - 0s 

In [6]:
model.predict(test_x)

array([[0.85012555, 0.12714861, 0.02272582],
       [0.00638677, 0.31687766, 0.6767355 ],
       [0.875243  , 0.1094247 , 0.01533238],
       [0.02054534, 0.4004582 , 0.5789964 ],
       [0.8956806 , 0.09258441, 0.01173497],
       [0.02927402, 0.43139952, 0.5393264 ],
       [0.00223343, 0.2648046 , 0.732962  ],
       [0.05952323, 0.49470267, 0.4457741 ],
       [0.8933965 , 0.09512122, 0.01148229],
       [0.01113496, 0.37975252, 0.60911244],
       [0.86575896, 0.11570369, 0.01853729],
       [0.8853292 , 0.10076308, 0.01390777],
       [0.0614743 , 0.47748503, 0.46104065],
       [0.00479678, 0.31614643, 0.67905676],
       [0.00661619, 0.34034064, 0.65304315],
       [0.9389458 , 0.05529105, 0.00576324],
       [0.12010309, 0.4952623 , 0.38463467],
       [0.08963058, 0.49471593, 0.41565356],
       [0.9192872 , 0.07253987, 0.00817294],
       [0.01347099, 0.35781527, 0.6287137 ],
       [0.8716923 , 0.11030401, 0.01800372],
       [0.06233901, 0.517301  , 0.42035997],
       [0.

In [7]:
predicted = model.predict_classes(test_x)
print(predicted)

[0 2 0 2 0 2 2 1 0 2 0 0 1 2 2 0 1 1 0 2 0 1 1 2 1 2 2 2 1 0 0 1 0 2 1 0 2
 2 0 0 2 0 2 1 0 1 2 0 1 1 2 1 2 0 0 1 1 2 2 2 0 2 2 2 1 2 2 2 2 0 0 2 1 1
 2]


In [8]:
for i in range(30):
    print(test_y[i],np.argmax(test_y[i]),predicted[i])

[1. 0. 0.] 0 0
[0. 0. 1.] 2 2
[1. 0. 0.] 0 0
[0. 1. 0.] 1 2
[1. 0. 0.] 0 0
[0. 0. 1.] 2 2
[0. 0. 1.] 2 2
[0. 1. 0.] 1 1
[1. 0. 0.] 0 0
[0. 0. 1.] 2 2
[1. 0. 0.] 0 0
[1. 0. 0.] 0 0
[0. 1. 0.] 1 1
[0. 0. 1.] 2 2
[0. 0. 1.] 2 2
[1. 0. 0.] 0 0
[0. 1. 0.] 1 1
[0. 1. 0.] 1 1
[1. 0. 0.] 0 0
[0. 0. 1.] 2 2
[1. 0. 0.] 0 0
[0. 1. 0.] 1 1
[0. 1. 0.] 1 1
[0. 0. 1.] 2 2
[0. 1. 0.] 1 1
[0. 0. 1.] 2 2
[0. 1. 0.] 1 2
[0. 1. 0.] 1 2
[0. 1. 0.] 1 1
[1. 0. 0.] 0 0


In [9]:
from sklearn.metrics import confusion_matrix
actual_label = np.argmax(test_y,axis=1)
confusion_matrix(actual_label, predicted)

array([[23,  0,  0],
       [ 0, 20,  7],
       [ 0,  0, 25]], dtype=int64)

In [10]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(actual_label, predicted)
accuracy

0.9066666666666666

In [11]:
from sklearn.metrics import recall_score
recall = recall_score(actual_label, predicted, average='macro')
recall

0.9135802469135802

In [12]:
from sklearn.metrics import precision_score
precision = precision_score(actual_label, predicted, average='macro')
precision

0.9270833333333334

In [13]:
from sklearn.metrics import f1_score
f1 = f1_score(actual_label, predicted, average='macro')
f1

0.9094189374144581