```
[Title] MLP Classification using Tensorflow.Keras
[Author] Yibeck Lee(yibec.Lee@gmail.com)
[Contents]
 - Multi-Layer Perceptron Classification for Prediction
```

In [2]:
"""
    A simple neural network written in Keras (TensorFlow backend) to classify the IRIS data
"""

import numpy as np

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam
import pandas as pd

# data = load_iris() # load the iris dataset
df = pd.read_csv("../data_source/iris.csv")
data = df.values

FEATURES = data[:,:4]
LABEL = data[:,-1]
LABEL

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [3]:

x = FEATURES
y_ = LABEL.reshape(-1, 1) # Convert data to a single column
y_ 

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],

In [4]:
# One Hot encode the class labels
encoder = OneHotEncoder(sparse=False)
y = encoder.fit_transform(y_)
print(y)


[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0.

C:\Apps\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [5]:
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.50)

In [6]:
# Split the data for training and testing


# Build the model

model = Sequential()

model.add(Dense(10, input_shape=(4,), activation='relu', name='fc1'))
model.add(Dense(20, activation='relu', name='fc2'))
model.add(Dense(20, activation='relu', name='fc3'))
model.add(Dense(3, activation='softmax', name='output'))

# Adam optimizer with learning rate of 0.001
optimizer = Adam(lr=0.001)
model.compile(optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

print('Neural Network Model Summary: ')
print(model.summary())

# Train the model
model.fit(train_x, train_y, verbose=2, batch_size=5, epochs=200)

# Test on unseen data

results = model.evaluate(test_x, test_y)

print('Final test set loss: {:4f}'.format(results[0]))
print('Final test set accuracy: {:4f}'.format(results[1]))

Neural Network Model Summary: 
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
fc1 (Dense)                  (None, 10)                50        
_________________________________________________________________
fc2 (Dense)                  (None, 20)                220       
_________________________________________________________________
fc3 (Dense)                  (None, 20)                420       
_________________________________________________________________
output (Dense)               (None, 3)                 63        
Total params: 753
Trainable params: 753
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/200
 - 1s - loss: 1.2036 - acc: 0.2533
Epoch 2/200
 - 0s - loss: 1.0950 - acc: 0.3867
Epoch 3/200
 - 0s - loss: 1.0694 - acc: 0.4133
Epoch 4/200
 - 0s - loss: 1.0488 - acc: 0.4133
Epoch 5/200
 - 0s - loss: 1.0325 - acc: 0.4133
Epoch

 - 0s - loss: 0.0549 - acc: 0.9867
Epoch 153/200
 - 0s - loss: 0.0627 - acc: 0.9733
Epoch 154/200
 - 0s - loss: 0.0443 - acc: 0.9867
Epoch 155/200
 - 0s - loss: 0.0528 - acc: 0.9867
Epoch 156/200
 - 0s - loss: 0.0501 - acc: 0.9867
Epoch 157/200
 - 0s - loss: 0.0481 - acc: 0.9867
Epoch 158/200
 - 0s - loss: 0.0592 - acc: 0.9733
Epoch 159/200
 - 0s - loss: 0.0498 - acc: 0.9867
Epoch 160/200
 - 0s - loss: 0.0462 - acc: 0.9867
Epoch 161/200
 - 0s - loss: 0.0492 - acc: 0.9867
Epoch 162/200
 - 0s - loss: 0.0469 - acc: 0.9867
Epoch 163/200
 - 0s - loss: 0.0479 - acc: 0.9867
Epoch 164/200
 - 0s - loss: 0.0447 - acc: 0.9867
Epoch 165/200
 - 0s - loss: 0.0524 - acc: 0.9867
Epoch 166/200
 - 0s - loss: 0.0716 - acc: 0.9600
Epoch 167/200
 - 0s - loss: 0.0676 - acc: 0.9467
Epoch 168/200
 - 0s - loss: 0.0519 - acc: 0.9867
Epoch 169/200
 - 0s - loss: 0.0518 - acc: 0.9867
Epoch 170/200
 - 0s - loss: 0.0539 - acc: 0.9733
Epoch 171/200
 - 0s - loss: 0.0603 - acc: 0.9867
Epoch 172/200
 - 0s - loss: 0.0461

In [7]:
model.predict(test_x)

array([[8.13360384e-05, 9.96922791e-01, 2.99587520e-03],
       [9.99999404e-01, 5.59531259e-07, 2.66233674e-10],
       [9.99991179e-01, 8.76522427e-06, 4.69215822e-09],
       [4.50318439e-05, 9.79507506e-01, 2.04473734e-02],
       [2.35934913e-05, 9.99846816e-01, 1.29617270e-04],
       [9.99994993e-01, 4.97477049e-06, 3.08912429e-09],
       [8.15874839e-04, 9.99001801e-01, 1.82274627e-04],
       [7.22599395e-07, 4.70833816e-02, 9.52915847e-01],
       [1.83012702e-11, 1.15812481e-05, 9.99988437e-01],
       [9.99999285e-01, 7.30914110e-07, 3.45393852e-10],
       [2.13746820e-09, 5.51083504e-05, 9.99944925e-01],
       [2.64156830e-09, 1.64961122e-04, 9.99835014e-01],
       [1.97719652e-04, 9.99550283e-01, 2.52018857e-04],
       [8.77363604e-08, 2.53584590e-02, 9.74641383e-01],
       [9.99997139e-01, 2.88643514e-06, 3.14900128e-09],
       [3.25033507e-05, 9.99733150e-01, 2.34292544e-04],
       [7.55912277e-10, 5.92845354e-05, 9.99940753e-01],
       [9.99999881e-01, 1.02563

In [8]:
predicted = model.predict_classes(test_x)
print(predicted)

[1 0 0 1 1 0 1 2 2 0 2 2 1 2 0 1 2 0 0 0 1 0 1 2 1 2 2 0 2 0 1 2 2 1 2 1 1
 2 2 2 0 2 0 2 2 2 0 1 2 2 2 0 0 2 0 2 0 1 0 0 0 0 0 1 2 2 1 2 1 2 2 0 1 1
 2]


In [9]:
for i in range(30):
    print(test_y[i],np.argmax(test_y[i]),predicted[i])

[0. 1. 0.] 1 1
[1. 0. 0.] 0 0
[1. 0. 0.] 0 0
[0. 1. 0.] 1 1
[0. 1. 0.] 1 1
[1. 0. 0.] 0 0
[0. 1. 0.] 1 1
[0. 0. 1.] 2 2
[0. 0. 1.] 2 2
[1. 0. 0.] 0 0
[0. 0. 1.] 2 2
[0. 0. 1.] 2 2
[0. 1. 0.] 1 1
[0. 0. 1.] 2 2
[1. 0. 0.] 0 0
[0. 1. 0.] 1 1
[0. 0. 1.] 2 2
[1. 0. 0.] 0 0
[1. 0. 0.] 0 0
[1. 0. 0.] 0 0
[0. 1. 0.] 1 1
[1. 0. 0.] 0 0
[0. 1. 0.] 1 1
[0. 0. 1.] 2 2
[0. 1. 0.] 1 1
[0. 0. 1.] 2 2
[0. 0. 1.] 2 2
[1. 0. 0.] 0 0
[0. 0. 1.] 2 2
[1. 0. 0.] 0 0


In [10]:
from sklearn.metrics import confusion_matrix
actual_label = np.argmax(test_y,axis=1)
confusion_matrix(actual_label, predicted)

array([[24,  0,  0],
       [ 0, 18,  1],
       [ 0,  2, 30]], dtype=int64)

In [11]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(actual_label, predicted)
accuracy

0.96

In [12]:
from sklearn.metrics import recall_score
recall = recall_score(actual_label, predicted, average='macro')
recall

0.9616228070175438

In [13]:
from sklearn.metrics import precision_score
precision = precision_score(actual_label, predicted, average='macro')
precision

0.9559139784946237

In [14]:
from sklearn.metrics import f1_score
f1 = f1_score(actual_label, predicted, average='macro')
f1

0.9584859584859585